package cluedoPieces;

public interface Card {

	enum WeaponType{
		CANDLESTICK,DAGGER,LEAD_PIPE,
		REVOLVER,ROPE,SPANNER
	}

	enum Person{
		SCARLETT,MUSTARD,WHITE,REVEREND,PEACOCK,PLUM
	}

	enum RoomType {
		KITCHEN,BALLROOM,CONSERVATORY,DINING_ROOM,
		BILLIARD_ROOM,LIBRARY,LOUNGE,HALL,
		STUDY
	}

}
